AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Clumio Lambda for Executing Mass VM Recoveries'

Resources:
  RecoveryLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.recover
      Runtime: python3.8
      CodeUri: S3 URL FOR YOUR ZIPFILE WITH DEPENDENCIES
      Description: Clumio function for recovering virtual machines
      MemorySize: 1024
      Timeout: 600
      Policies:
      - AWSLambdaExecute
      - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          bucket: bucketname
          creds: jsonfilename
          csv: recoveryplanCSV
