AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Clumio tool for tagging and untagging EBS and RDS snapshots

Resources:

  
  RecoveryLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: recovery.app.recover
      Runtime: python3.8
      CodeUri: recovery.zip
      Description: 'Clumio function for tagging EBS and RDS snapshot'
      MemorySize: 1024
      Timeout: 600
      Policies: 
        - AWSLambdaExecute
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          bucket: bucketname
          creds: jsonfilename
          csv: recoveryplanCSV
